[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rayon = "1.10.0"
itertools = "0.13.0"
nalgebra = "0.33.2"
image = "0.24.5"

[lints.rust]
unused_imports = "allow"